[package]
name = "axolotlclient-api"
version = "0.0.0"
edition = "2021"

[dependencies]
anyhow = "1"
base64 = "0.22"
blake2 = "0.10"
env_logger = "0.11"
log = "0.4"
rand = "0.8"
serde_urlencoded = "0.7"
thiserror = "1"
axum_garde = "0.18"

garde = { version = "0.18", features = ["derive", "regex"] }

[dependencies.axum]
version = "0.7"
default-features = false
features = ["http1", "json", "query", "tokio", "ws"]

[dependencies.chrono]
version = "0.4"
features = ["serde"]

[dependencies.reqwest]
version = "0.11"
features = ["json"]

[dependencies.serde]
version = "1"
features = ["derive"]

[dependencies.sqlx]
version = "0.7"
default-features = false
features = ["chrono", "macros", "migrate", "runtime-tokio", "sqlite", "tls-none", "uuid"]

[dependencies.tokio]
version = "1"
features = ["net", "rt-multi-thread"]

[dependencies.uuid]
version = "1"
features = ["serde", "v4"]
