on: push
env:
  CARGO_TERM_COLOR: always
jobs:
  cargo:
    name: Cargo
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_HOST_AUTH_METHOD: trust
          POSTGRES_DB: axolotl_client-api
        ports:
          - "127.0.0.1:5432:5432"
    steps:
      - uses: actions/checkout@v4
      - uses: swatinem/rust-cache@v2
      - uses: cachix/install-nix-action@v26
      - uses: cachix/cachix-action@v14
      - run: nix profile install nixpkgs#devenv
      - run: devenv shell sqlx migrate run
      - run: devenv shell cargo fmt --check
      - run: devenv shell cargo build
      - run: |
          devenv cargo clippy --all-features --message-format=json-diagnostic-rendered-ansi | jq -r 'select(.reason == "compiler-message").message | . as {message: $message, level: $level, rendered: $rendered} | .spans[] | select(.is_primary == true) | "::" + $level + " file=" + .file_name + ",col=" + (.column_start | tostring) + ",endColumn=" + (.column_end | tostring) + ",line=" + (.line_start | tostring) + ",endLine=" + (.line_end | tostring) + "::" + $message + "\n" + $rendered'
          exit ${PIPESTATUS[0]}
